version: '3'

services:

  builder:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - webdata:/web

  nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - webdata:/web
    depends_on:
      - php-fpm
      - builder
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ..
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - webdata:/web
    depends_on:
      - builder

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - webdata:/web
    environment:
      - NODE_ENV=development
    depends_on:
      - builder

volumes:
    webdata:
