version: '3'

services:

  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - webdata:/web
    environment:
      - NODE_ENV=development
    depends_on:
      - builder
    ports:
      - "5000:5000"

volumes:
    webdata:
